name: Publish hasher CLI tool for Windows / macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish for macOS
      run: dotnet publish -c Release --self-contained -r osx-x64 -o output -p:AssemblyName=hasher-mac-x64 Console/Console.csproj
    - name: Publish for Windows
      run: dotnet publish -c Release --self-contained -r win-x64 -o output -p:AssemblyName=hasher-win-x64 Console/Console.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: hasher
        path: ./output/*
        if-no-files-found: error  
        retention-days: 30  
        include-hidden-files: false
